from pymongo_get_database import get_database

chychoVault = get_database()
posts = chychoVault["posts3"]


titles = ("Synopsis of Our Present Predicament: What the Future Holds, a Final Word ",
    "The Best Advice Regarding the Importance of Education That You Will Ever Hear: Some Wise Words from Ex-child Soldier, Omar Khadr ",
     "The Subjugation of Africa, the Battle for a Continent: Full Throttle into Oblivion",
     "For the Age of the Information Wars, Some Pertinent Quotes Regarding the Future of Humanity: Stephen Hawking, Carl Sagan, Isaac Asimov, John F. Kennedy, William Thurston, Jacob Appelbaum, and Assata Shakur",
     "Heads-up Canada, B.C. Government Has Given Industry Access to Our Parks: A Drift Card I Found on the Beach",
     "Would Bankruptcy Protect You from Being Prosecuted for Murder? Then Why Are GM and Its Officers Getting Immunity for Deaths That They Could Have Prevented for $1 per Car?",
     "Google’s CEO Larry Page on Improving the World, NSA, Security, and Tesla: TED Talks Interview That Can Make You Smile If You’re Oblivious or Make You Want to Vomit If You’re in the Know",
     "Actual Jubilation in Crimea vs. Orchestrated Celebration in Iraq: Can You Spot the Difference?",
     "The Hypocrisy Is Unbearable: Iraq vs. Crimea, Can You Spot the Difference?",
     "From the Pages of Barry Ween: What We Would All Like to Do and Say to the Minions of the Surveillance State",
     "NSA’s Desperation for Secrecy Leads to Stupidity, Alienating the Hacker Community: ‘Freedom Downtime’, a Call to Arms",
     "What’s Really Going On: Bahrain vs. Ukraine, Can You Spot the Difference?",
     "Regarding Liz Wahl and Abby Martin, Just a Reminder That Phil Donahue Was Crucified Twice in America for Opposing War with Iraq",
     "Information War Kicks into High Gear on Reddit: A List of Open Subreddits and How to Deal with Censorship",
     "Two plus Two Does Not Equal Five: Will the Real Terrorist and Drug Lords Please Stand up",
     "It’s Not the Economy Stupid, It’s Your Stupid Foreign Policy: How to Get Rid of Our Oligarchs",
     "A Music Video from Egypt with a Message: “Some people are dancing and others are dying, and the loudest voice in the party is the voice of silence”, Cairokee",
     "When Mainstream Media’s Narrative Collapses: Building 7",
     "What Cold War?",
     "The Irony and the Hypocrisy, the U.S. Department of Defense Is Using Blackberry for Its Privacy",
     "Excellent Interview and Discussion on the Current State of Affairs in Turkey and What the Future May Hold for the Region",
     "It’s Not Just the Mainstream Media That Is Scripted to Manufacture Consent, so Are Our Politicians",
     "Here Is What Happened in Fallujah in 2004, a Prelude for What Is to Come in 2014",
     "The Dominoes Are Falling, the Tides Are Turning, the War on Drugs Is Ending, but Prohibitionists Just Won’t Give up the Ghost: How to End Prohibition",
     "1997 Address by Nelson Mandela at the International Day of Solidarity with the Palestinian People",
     "America: Afraid of Shadows in the Dark While Ignoring the Elephants in the Room",
     "Chris Hedges' Introduction to Inverted Totalitarianism from “Days of Destruction, Days of Revolt”",
     "Canadians Can Grow Tobacco for Personal Use; We Should Be Able to Do the Same with Cannabis",
     "The British Military, Operating Death Squads from Belfast to Basra: Terrorizing Civilians is What Occupying Forces Do",
     "The Six Primary Reasons for Why They Hate Us",
     "A Few Choice Words from Immortal Technique to Mainstream Media’s War Profiteering Pundits: “Shut the Fuck Up You Mindless Drone!”",
     "How to Protect Ourselves on Social Networks and from Data Collection Systems of Governments and Corporations",
     "Government Shutdown and Appointment of Janet Yellen Guarantees Flow of Funds to Wall Street: They are reducing “two-thirds of this country to subsistence level”, Chris Hedges",
     "An example of how the surveillance state is hurting the U.S. economy: Ladar Levison confirms that he will be forced to move his business overseas",
     "“Pretending that one can dissociate torture from war or abjection from massacre is the lie of the powerful”, ‘Ordinary Victories’ by Manu Larcenet",
     "Schooling Superman on Totalitarianism: Superman and The Flash have a discussion about gun control while playing chess",
     "In Recognition of Endless Wars and Those Who Profit From Them: The Savage Sword of Conan",
     "U.S. government knew that revelations about NSA’s PRISM program would hurt American Technology companies, but they didn’t “really really care”, Bart Gellman",
     "What will make or break the United States of America is the truth about 9/11: Investigate the theories behind the conspiracies",
     "Target is Still Iran: Clear Cutting the Middle East and the Coming Blood Bath (Mapping World War III)",
     "One, Two, Three",
     "Why the U.S. Government has such a hard-on for Edward Snowden",
     "Here is What’s Going On in Canada, Part 1: Two Telltale Speeches by Stephen Harper",
     "So let me get this straight, we fast track renditions but hunt down whistleblowers on presidential planes!",
     "World War III began in May 2006: Building the New Map of the Middle East in Real Time",
     "Noam Chomsky, a Conspiracy Theorist of the Highest Magnitude: Defining Conspiracy Theory, What are the Theories Behind the Conspiracies?",
     "The shit show that is Afghanistan: “We will survive. But they will be taking the war back to America!”",
     "Not-so-Random Information: Introduction and Table of Contents",
     "Democracy Now’s interview of Jeremy Scahill: Assassinations, Drones, Dirty Wars, Asymmetric Warfare, and Africa’s Bleak Future",
     "Sharing a Story from My Father: In Commemoration of the Armenian Genocide",
     "Creating torture centers and death squads in Iraq: Allowing psychopaths to abuse and rape children in the United States",
     "On this tenth anniversary of the invasion of Iraq, a reminder, according to the UN charter, the invasion was illegal",
     "Today, dedicate an hour of your life to watching Democracy Now’s coverage of Guatemala's Genocide Trial",
     "May I Recommend a Documentary: “The Wobblies”",
     "Recolonization of Africa, a Symptom of Our Addiction to Growth: Differential Accumulation, Why GDP Growth Rates Influence Foreign Policy",
     "France Has Forgotten the Battle of Algiers, Africa Never Will: “Ordinary Victories” by Manu Larcenet",
     "Western Powers Go Full Retard on Africa: China vs. AFRICOM, a Resource War",
     "Aaron Swartz, America’s Mohamed Bouazizi: We’re in the midst of a revolution, which side are you on?",
     "Lest we forget, an attack on Syria is an attack on Iran",
     "Obama’s Crocodile Tears and Madeleine Albright’s Hard Choices:",
     "A Dinner Conversation: Israel and Armenia, Oppression and Genocides, Reality and Denials",
     "Bradley Manning and the trial of the United States Military",
     "An Apology from Canada to Palestine and the Rest of the World",
     "Ominous Forewarning from Prof. Norman Finkelstein",
     "Regarding Israel and Palestine, and the new offensive in Gaza",
     "What to Expect from the Obama Administration for the Next Four Years",
     "The Presidential Debate that Most Americans Didn’t See, and Why",
     "A Candid Speaker and Three Hypocrites address the 67th session of the United Nations General Assembly",
     "Dahr Jamail on what happened in Fallujah")


for title in titles:
    posts.find_one_and_update({'title': {"$regex": title}},{'$push':{'tag':'politics'}})